clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-6
    environment:
      - APP_NAME=updater
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    when:
      matrix:
        TESTS: signed-off-check
  check-same-code-base:
    image: nextcloudci/php7.0:php7.0-6
    commands:
      - make check-same-code-base
    when:
      matrix:
        TESTS: check-same-code-base
  php54-cli:
    image: nextcloudci/php5.4:php5.4-5
    commands:
      - make test-cli
    when:
      matrix:
        TESTS: php54-cli
  php55-cli:
    image: nextcloudci/php5.5:php5.5-5
    commands:
      - make test-cli
    when:
      matrix:
        TESTS: php55-cli
  php56-cli:
    image: nextcloudci/php5.6:php5.6-7
    commands:
      - make test-cli
    when:
      matrix:
        TESTS: php56-cli
  php70-cli:
    image: nextcloudci/php7.0:php7.0-6
    commands:
      - make test-cli
    when:
      matrix:
        TESTS: php70-cli
  php71-cli:
    image: nextcloudci/php7.1:php7.1-9
    commands:
      - make test-cli
    when:
      matrix:
        TESTS: php71-cli
  php54-stable9:
    image: nextcloudci/php5.4:php5.4-5
    commands:
      - make test-stable9
    when:
      matrix:
        TESTS: php54-stable9
  php55-stable9:
    image: nextcloudci/php5.5:php5.5-5
    commands:
      - make test-stable9
    when:
      matrix:
        TESTS: php55-stable9
  php56-stable9:
    image: nextcloudci/php5.6:php5.6-7
    commands:
      - make test-stable9
    when:
      matrix:
        TESTS: php56-stable9
  php70-stable9:
    image: nextcloudci/php7.0:php7.0-6
    commands:
      - make test-stable9
    when:
      matrix:
        TESTS: php70-stable9
  php56-stable10:
    image: nextcloudci/php5.6:php5.6-7
    commands:
      - make test-stable10
    when:
      matrix:
        TESTS: php56-stable10
  php70-stable10:
    image: nextcloudci/php7.0:php7.0-6
    commands:
      - make test-stable10
    when:
      matrix:
        TESTS: php70-stable10
  php54-master:
    image: nextcloudci/php5.4:php5.4-5
    commands:
      - make test-master
    when:
      matrix:
        TESTS: php54-master
  php56-stable11:
    image: nextcloudci/php5.6:php5.6-7
    commands:
      - make test-stable11
    when:
      matrix:
        TESTS: php56-stable11
  php70-stable11:
    image: nextcloudci/php7.0:php7.0-6
    commands:
      - make test-stable11
    when:
      matrix:
        TESTS: php70-stable11
  php71-stable11:
    image: nextcloudci/php7.1:php7.1-9
    commands:
      - make test-stable11
    when:
      matrix:
        TESTS: php71-stable11
  php56-master:
    image: nextcloudci/php5.6:php5.6-7
    commands:
      - make test-master
    when:
      matrix:
        TESTS: php56-master
  php70-master:
    image: nextcloudci/php7.0:php7.0-6
    commands:
      - make test-master
    when:
      matrix:
        TESTS: php70-master
  php71-master:
    image: nextcloudci/php7.1:php7.1-9
    commands:
      - make test-master
    when:
      matrix:
        TESTS: php71-master
matrix:
  include:
    #- TESTS: php54-cli # TODO currently the php built in server can't be used
    - TESTS: php55-cli
    - TESTS: php56-cli
    - TESTS: php70-cli
    #- TESTS: php71-cli - not supported on Nextcloud up to 10
    #- TESTS: php54-stable9 # TODO currently the php built in server can't be used
    - TESTS: php55-stable9
    - TESTS: php56-stable9
    - TESTS: php70-stable9
    - TESTS: php56-stable10
    - TESTS: php70-stable10
    - TESTS: php56-stable11
    - TESTS: php70-stable11
    - TESTS: php71-stable11
    - TESTS: php56-master
    - TESTS: php70-master
    - TESTS: php71-master
    - TESTS: signed-off-check
    - TESTS: check-same-code-base

branches: [ master, stable* ]
