kind: pipeline
name: check-same-code-base

steps:
  - name: check-same-code-base
    image: nextcloudci/php7.0:php7.0-19
    commands:
      - make check-same-code-base

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php70-cli

steps:
  - name: php70-cli
    image: nextcloudci/php7.0:php7.0-19
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php71-cli

steps:
  - name: php71-cli
    image: nextcloudci/php7.1:php7.1-16
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php71-master

steps:
  - name: php71-master
    image: nextcloudci/php7.1:php7.1-16
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php72-master

steps:
  - name: php72-master
    image: nextcloudci/php7.2:php7.2-12
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-master

steps:
  - name: php73-master
    image: nextcloudci/php7.3:php7.3-2
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
