pipeline:
  clone:
    image: plugins/git
    depth: 1
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-4
    environment:
      - APP_NAME=updater
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    when:
      matrix:
        TESTS: signed-off-check
  check-same-code-base:
    image: nextcloudci/php7.0:php7.0-4
    commands:
      - make check-same-code-base
    when:
      matrix:
        TESTS: check-same-code-base
  test-cli-php54:
    image: nextcloudci/php5.4:php5.4-3
    commands:
      - make test
    when:
      matrix:
        TESTS: test-php54
  test-cli-php55:
    image: nextcloudci/php5.5:php5.5-3
    commands:
      - make test
    when:
      matrix:
        TESTS: test-php55
  test-cli-php56:
    image: nextcloudci/php5.6:php5.6-4
    commands:
      - make test
    when:
      matrix:
        TESTS: test-php56
  test-cli-php70:
    image: nextcloudci/php7.0:php7.0-4
    commands:
      - make test
    when:
      matrix:
        TESTS: test-php70
  test-cli-php71:
    image: nextcloudci/php7.1:php7.1-8
    commands:
      - make test
    when:
      matrix:
        TESTS: test-php71
matrix:
  include:
    - TESTS: test-php54
    - TESTS: test-php55
    - TESTS: test-php56
    - TESTS: test-php70
    - TESTS: test-php71
    - TESTS: signed-off-check
    - TESTS: check-same-code-base
